name: Jira Exporter Workflow

on:
  workflow_dispatch:    # <-- manual trigger support
  schedule:
    - cron: '0 */1 * * *'  # runs every hour test 6 PR

jobs:
  run-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: port-labs/ocean-sail@v1
        with:
          type: 'jira'
          port_client_id: ${{ secrets.OCEAN__PORT__CLIENT_ID }}
          port_client_secret: ${{ secrets.OCEAN__PORT__CLIENT_SECRET }}
          port_base_url: https://api.getport.io
          config: |
            jira_host: ${{ secrets.OCEAN__INTEGRATION__CONFIG__JIRA_HOST }}
            atlassian_user_email: ${{ secrets.OCEAN__INTEGRATION__CONFIG__ATLASSIAN_USER_EMAIL }}
            atlassian_user_token: ${{ secrets.OCEAN__INTEGRATION__CONFIG__ATLASSIAN_USER_TOKEN }}
